import { tableProps } from "../types/homeTable";
export  const tableData:tableProps[] = [
    {
      id: 1,
      name: "Abdur Rahman",
      price: 450.50,
      status: "active",
      category: "Electronics",
      date: "2024-03-10",
    },
    {
      id: 2,
      name: "Mir Monir",
      price: 120.00,
      status: "pending",
      category: "Gadgets",
      date: "2024-03-05",
    },
    {
      id: 3,
      name: "Sabbir Ahmed",
      price: 500.00,
      status: "active",
      category: "Home Decor",
      date: "2024-03-15",
    },
    {
      id: 4,
      name: "Zayan Malik",
      price:75.25,
      status: "inactive",
      category: "Stationary",
      date: "2024-02-28",
    },
    {
      id: 5,
      name: "Jannatul Fardous",
      price: 1250.00,
      status: "active",
      category: "Fashion",
      date: "2024-01-20",
    },
    {
      id: 6,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
    {
      id: 6,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
    {
      id: 7,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
    {
      id: 8,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
    {
      id: 9,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
    {
      id: 10,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
    {
      id: 11,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
    {
      id: 12,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
    {
      id: 13,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
    {
      id: 14,
      name: "Ariful Islam",
      price: 320.00,
      status: "pending",
      category: "Books",
      date: "2024-03-01",
    },
  ];